#!/bin/sh
#
# Start logging
#

case "$1" in
  start)
	echo -n "Starting modes: "
	exec /modes/*
	# start-stop-daemon -b -S -q -m -p /var/run/syslogd.pid --exec /sbin/syslogd -- -n
	# start-stop-daemon -b -S -q -m -p /var/run/klogd.pid --exec /sbin/klogd -- -n
	echo "OK"
	;;
  stop)
	# start-stop-daemon -K -q -p /var/run/syslogd.pid
	# start-stop-daemon -K -q -p /var/run/klogd.pid
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
